name: Run Selenium Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout web app (Repo A)
      uses: actions/checkout@v4

    - name: Serve HTML files
      run: |
        npx http-server . -p 8080 &
        sleep 5

    - name: Checkout Selenium Tests (Repo B)
      uses: actions/checkout@v4
      with:
        repository: jordnkr/SeleniumDemo2025
        token: ${{ secrets.PAT }}
        path: selenium-tests

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Fix Selenium Manager permissions
      run: |
        chmod +x selenium-tests/SeleniumDemo2025/bin/Debug/net8.0/selenium-manager/linux/selenium-manager || true

    - name: Run Selenium Tests
      run: |
        cd selenium-tests
        dotnet restore
        dotnet test
