name: Run Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Testable UI
      uses: actions/checkout@v4

    - name: Serve HTML files
      run: |
        npx http-server . -p 8080 &
        sleep 5

    - name: Checkout Playwright Tests
      uses: actions/checkout@v4
      with:
        repository: jordnkr/playwright-testing-suite-demo
        token: ${{ secrets.PAT }}
        path: playwright-tests

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install deps for tests
      working-directory: playwright-tests
      run: |
        npm ci

    # Install Playwright browsers and OS dependencies
    - name: Install Playwright Browsers
      working-directory: playwright-tests
      run: |
        npx playwright install chromium
      # npx playwright install --with-deps this does full install for all browsers

    - name: Run functional tests for testable-ui
      working-directory: playwright-tests
      run: |
        npx playwright test src/projects/testable-ui --grep "@a11y" --project=chromium

    - name: Upload Playwright HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-tests/playwright-report


# name: Run Selenium Tests

# on:
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout web app (Repo A)
#       uses: actions/checkout@v4

#     - name: Serve HTML files
#       run: |
#         npx http-server . -p 8080 &
#         sleep 5

#     - name: Checkout Selenium Tests (Repo B)
#       uses: actions/checkout@v4
#       with:
#         repository: jordnkr/SeleniumDemo2025
#         token: ${{ secrets.PAT }}
#         path: selenium-tests

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: '8.x'

#     - name: Fix Selenium Manager permissions
#       run: |
#         chmod +x selenium-tests/SeleniumDemo2025/bin/Debug/net8.0/selenium-manager/linux/selenium-manager || true

#     - name: Run Selenium Tests
#       run: |
#         cd selenium-tests
#         dotnet restore
#         dotnet test
